package tabledemo;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Calculator extends javax.swing.JFrame {

     private double total1 = 0.0;
    private double total2 = 0.0;
    private double pi=3.1415926535898;
    private char math_operator;
    /** Creates new form Calculator */
    
    private void getOperator(String btnText)
    {
    math_operator= btnText.charAt(0);
    total1 = total1 + Double.parseDouble( txtDisplay.getText( ) ) ;
    txtDisplay.setText("");
    
    }
    private void r(String btnText)
    {
       total1 = total1 + Double.parseDouble( txtDisplay.getText( ) ) ;
       txtDisplay.setText("");
    }
    public Calculator() {
        super("Scientific Calculator Made By Tuhin");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btn_x = new javax.swing.JButton();
        btn_sqr = new javax.swing.JButton();
        btn_cos = new javax.swing.JButton();
        btn_sin = new javax.swing.JButton();
        btn_tan = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_pi = new javax.swing.JButton();
        plusminus = new javax.swing.JButton();
        btn_sqrt = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();
        btn_fact = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        txtDisplay.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        txtDisplay.setForeground(new java.awt.Color(0, 102, 102));
        txtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayActionPerformed(evt);
            }
        });

        btnOne.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnOne.setForeground(new java.awt.Color(0, 102, 102));
        btnOne.setText("1");
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnTwo.setForeground(new java.awt.Color(0, 102, 102));
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnThree.setForeground(new java.awt.Color(0, 102, 102));
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnPlus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(0, 102, 102));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnFour.setForeground(new java.awt.Color(0, 102, 102));
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnFive.setForeground(new java.awt.Color(0, 102, 102));
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnSix.setForeground(new java.awt.Color(0, 102, 102));
        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnMinus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(0, 102, 102));
        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnSeven.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnSeven.setForeground(new java.awt.Color(0, 102, 102));
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnEight.setForeground(new java.awt.Color(0, 102, 102));
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnNine.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnNine.setForeground(new java.awt.Color(0, 102, 102));
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnMul.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnMul.setForeground(new java.awt.Color(0, 102, 102));
        btnMul.setText("*");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 102, 102));
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnZero.setForeground(new java.awt.Color(0, 102, 102));
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnEqual.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnEqual.setForeground(new java.awt.Color(0, 102, 102));
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnDivide.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnDivide.setForeground(new java.awt.Color(0, 102, 102));
        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btn_x.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_x.setForeground(new java.awt.Color(0, 102, 102));
        btn_x.setText("1/x");
        btn_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xActionPerformed(evt);
            }
        });

        btn_sqr.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_sqr.setForeground(new java.awt.Color(0, 102, 102));
        btn_sqr.setText("x2");
        btn_sqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqrActionPerformed(evt);
            }
        });

        btn_cos.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_cos.setForeground(new java.awt.Color(0, 102, 102));
        btn_cos.setText("cos");
        btn_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cosActionPerformed(evt);
            }
        });

        btn_sin.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_sin.setForeground(new java.awt.Color(0, 102, 102));
        btn_sin.setText("sin");
        btn_sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sinActionPerformed(evt);
            }
        });

        btn_tan.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_tan.setForeground(new java.awt.Color(0, 102, 102));
        btn_tan.setText("tan");
        btn_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tanActionPerformed(evt);
            }
        });

        btn_dot.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_dot.setForeground(new java.awt.Color(0, 102, 102));
        btn_dot.setText(".");
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });

        btn_pi.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_pi.setForeground(new java.awt.Color(0, 102, 102));
        btn_pi.setText("pi");
        btn_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_piActionPerformed(evt);
            }
        });

        plusminus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        plusminus.setForeground(new java.awt.Color(0, 102, 102));
        plusminus.setText("+/_");
        plusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminusActionPerformed(evt);
            }
        });

        btn_sqrt.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_sqrt.setForeground(new java.awt.Color(0, 102, 102));
        btn_sqrt.setText("√");
        btn_sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sqrtActionPerformed(evt);
            }
        });

        btn_log.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_log.setForeground(new java.awt.Color(0, 102, 102));
        btn_log.setText("log");
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        btn_fact.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_fact.setForeground(new java.awt.Color(0, 102, 102));
        btn_fact.setText("n!");
        btn_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_factActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisplay)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnFour)
                                .addGap(18, 18, 18)
                                .addComponent(btnFive)
                                .addGap(18, 18, 18)
                                .addComponent(btnSix))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_sin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnOne)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTwo)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnThree))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnSeven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEight)
                                            .addComponent(btnZero))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnEqual)
                                            .addComponent(btnNine))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClear)
                                    .addComponent(btn_pi, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_fact, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .addComponent(btnMul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(plusminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_sqr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1))
                                    .addComponent(btn_x, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOne)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnTwo)
                                        .addComponent(btnThree)))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnFive)
                                        .addComponent(btnFour))
                                    .addComponent(btnSix)))
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEight)
                                .addComponent(btnSeven))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNine)
                                .addComponent(btnMul)
                                .addComponent(btn_sqr)
                                .addComponent(btn_fact))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPlus)
                            .addComponent(btn_sqrt))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMinus)
                            .addComponent(btn_x))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dot)
                    .addComponent(btnZero)
                    .addComponent(btnEqual)
                    .addComponent(btnDivide)
                    .addComponent(btn_pi)
                    .addComponent(plusminus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sin)
                    .addComponent(btn_cos)
                    .addComponent(btn_tan)
                    .addComponent(btn_log))
                .addGap(43, 43, 43))
        );

        jMenu1.setText("View");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
//        String btnOneText = btnOne.getText( );
//        
        String btnOneText = txtDisplay.getText() + btnOne.getText();
        txtDisplay.setText(btnOneText);
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        String btnTwoText = txtDisplay.getText() + btnTwo.getText();
        txtDisplay.setText(btnTwoText);
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        String btnThreeText = txtDisplay.getText() + btnThree.getText();
        txtDisplay.setText(btnThreeText);
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed

        String button_text = btnPlus.getText();
        getOperator(button_text);
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        String btnFourText = txtDisplay.getText() + btnFour.getText();
        txtDisplay.setText(btnFourText);
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        String btnFiveText = txtDisplay.getText() + btnFive.getText();
        txtDisplay.setText(btnFiveText);
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        String btnSixText = txtDisplay.getText() + btnSix.getText();
        txtDisplay.setText(btnSixText);
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        String button_text = btnMinus.getText();
        getOperator(button_text);
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        String btnSevenText = txtDisplay.getText() + btnSeven.getText();
        txtDisplay.setText(btnSevenText);
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        String btnEightText = txtDisplay.getText() + btnEight.getText();
        txtDisplay.setText(btnEightText);
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        String btnNineText = txtDisplay.getText() + btnNine.getText();
        txtDisplay.setText(btnNineText);
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        String button_text = btnMul.getText();
        getOperator(button_text);
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        total2 = 0;
        txtDisplay.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        String btnZeroText = txtDisplay.getText() + btnZero.getText();
        txtDisplay.setText(btnZeroText);
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        switch (math_operator) {
            case '+':
                total2 = total1 + Double.parseDouble(txtDisplay.getText());
                break;
            case '-':
                total2 = total1 - Double.parseDouble(txtDisplay.getText());
                break;
            case '/':
                total2 = total1 / Double.parseDouble(txtDisplay.getText());
                break;
            case '*':
                total2 = total1 * Double.parseDouble(txtDisplay.getText());
                break;
            case '˄':
                total2 = Math.pow(total1, Double.parseDouble(txtDisplay.getText()));
                break;

        }

        //total2 = total1 + Double.parseDouble( txtDisplay.getText( ) ) ;
        txtDisplay.setText(Double.toString(total2));
        total1 = total2 = 0;
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        String button_text = btnDivide.getText();
        getOperator(button_text);
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btn_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xActionPerformed
        String btn_Text = btn_x.getText();
        r(btn_Text);
        total2 = 1.0 / (total1);
        txtDisplay.setText(Double.toString(total2));
        total1 = 0;
    }//GEN-LAST:event_btn_xActionPerformed

    private void btn_sqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqrActionPerformed
        String btn_Text = btn_sqr.getText();
        r(btn_Text);
        total2 = Math.pow(total1, 2);
        txtDisplay.setText(Double.toString(total2));
        total1 = 0;
    }//GEN-LAST:event_btn_sqrActionPerformed

    private void btn_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cosActionPerformed
        String btn_Text = btn_cos.getText();
        r(btn_Text);
        total2 = Math.toRadians(total1);
        if (total1 == 90 || total1 == 270 || total1 == 450 || total1 == 630 || total1 == 810) {
            txtDisplay.setText(String.format("0.0"));
        } 
        else if (total1 == -90 || total1 == -270 || total1 == -450 || total1 == -630 || total1 == -810) {
            txtDisplay.setText(String.format("0.0"));
        }
        else {
            txtDisplay.setText(Double.toString(Math.cos(total2)));
        }
        total1 = 0;
    }//GEN-LAST:event_btn_cosActionPerformed

    private void btn_sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sinActionPerformed
        String btn_Text = btn_sin.getText();
        r(btn_Text);
        total2 = Math.toRadians(total1);
        if (total1 == 180 || total1 == 360 || total1 == 720 || total1 == 14400) {
            txtDisplay.setText(String.format("0.0"));
        } 
        else if (total1 == -180 || total1 == -360 || total1 == -720 || total1 == -14400) {
            txtDisplay.setText(String.format("0.0"));
        } 
        else {
            txtDisplay.setText(Double.toString(Math.sin(total2)));
        }
        total1 = 0;
    }//GEN-LAST:event_btn_sinActionPerformed

    private void btn_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tanActionPerformed
        String btn_Text = btn_tan.getText();
        r(btn_Text);
        total2 = Math.toRadians(total1);
        if (total1 == 90 || total1 == 270 || total1 == 450 || total1 == 630 || total1 == 810) {
            txtDisplay.setText(String.format("∞"));
        } 
        else if (total1 == -90 || total1 == -270 || total1 == -450 || total1 == -630 || total1 == -810) {
            txtDisplay.setText(String.format("∞"));
        }
        else if (total1 == 0 || total1 == 180 || total1 == 360 || total1 == 720 || total1 == 1440) {
            txtDisplay.setText(String.format("0.0"));
        } 
        else if (total1 == -180 || total1 == -360 || total1 == -720 || total1 == -1440) {
            txtDisplay.setText(String.format("0.0"));
        }
        else {
            txtDisplay.setText(Double.toString(Math.tan(total2)));
        }
        total1 = 0;
    }//GEN-LAST:event_btn_tanActionPerformed

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
        String btn_Text = txtDisplay.getText() + btn_dot.getText();
        txtDisplay.setText(btn_Text);

    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_piActionPerformed
        String btn_Text = btn_pi.getText();
        // r( btn_Text );
        total2 = pi;
        txtDisplay.setText(Double.toString(total2));
        //total1 = 0;
    }//GEN-LAST:event_btn_piActionPerformed

    private void plusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminusActionPerformed
        String btn_Text = plusminus.getText();
        r(btn_Text);
        total2 = total1 * (-1);
        txtDisplay.setText(Double.toString(total2));
        total1 = 0;

    }//GEN-LAST:event_plusminusActionPerformed

    private void btn_sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sqrtActionPerformed
        String btn_Text = btn_sqrt.getText();
        r(btn_Text);
        total2 = Math.sqrt(total1);
        txtDisplay.setText(Double.toString(total2));
        total1 = 0;
    }//GEN-LAST:event_btn_sqrtActionPerformed

    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
        String btn_Text = btn_cos.getText();
        r(btn_Text);
        total2 = Math.log10(total1);
        txtDisplay.setText(Double.toString(total2));
        total1 = 0;
    }//GEN-LAST:event_btn_logActionPerformed

    private void btn_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_factActionPerformed
        String btn_Text = btn_cos.getText();
        r(btn_Text);
        double i, sum = 1;
        for (i = total1; i >= 1; i--) {
            sum = sum * i;
        }
        txtDisplay.setText(Double.toString(sum));
        total1 = 0;
    }//GEN-LAST:event_btn_factActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       // javax.swing.JOptionPane.showMessageDialog( javax.swing.JOptionPane.showMessageDialog( FormObjects.this,"Standard" );
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton btn_cos;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_fact;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_pi;
    private javax.swing.JButton btn_sin;
    private javax.swing.JButton btn_sqr;
    private javax.swing.JButton btn_sqrt;
    private javax.swing.JButton btn_tan;
    private javax.swing.JButton btn_x;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton plusminus;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
